:Author: (Prashant Kumar)[https://github.com/Krprashant94]
:Email: {kr.prashant94@gmail.com}
:Date: 03/02/2019
:Revision: 1.0.1
:License: MIT

= Project: BO motor uses in Arduino

This program is simple illustration of use og BO motor using motor driver module.

== Step 1: Installation
To use this pice of code download the Arduino software and run this code. This code is tested on Arduino Uno and Mega.

== Step 2: Assemble the circuit

Assemble the circuit as in layout.png

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Motor                        => Arduino sketch folder
  ├── Motor.ino               => main Arduino file
  ├── layout.png              => Circuit Diagram
  └── README.adoc             => this file
....

=== License
This project is released under a License given in root directory.
If you want to use any piece of code please cite me as given below

NOTE: P. K. Prasad, "Arduino Peripherals," 03-Feb-2019. [Online]. Available: https://github.com/Krprashant94/Arduino-Peripherals. [Accessed: 04-Feb-2019]

=== Contributing
To contribute this project please contact krprashant94 https://id.arduino.cc/krprashant94 or krprashant94 https://github.com/Krprashant94

=== BOM
Bill of the materials need for this project.

|===
| SL | Part name         | Model       | Quantity
| 1  | BO Motor          | 300 RPM     | 1
| 2  | Motor Driver      | l298N       | 1
| 3  | Arduino UNO       | R3          | 1
| 4  | Programming Cable | USB 2.0     | 1
|===


=== Help
Fell free to contact me for help